### ISSUE TITLE
upgrade to 2.5 needs pathogen-profiler 1.5

### ISSUE THREAD

**Issue by pmenzel** [jodyphelan/TBProfiler#47]
Hi,

I just had a similar issue as #39. After upgrading tb-profiler from 2.4 to 2.5 via conda and running `tb-profiler profile`, I got this error:
```
Traceback (most recent call last):
  File "/opt/conda/miniconda3/envs/ptr/bin/tb-profiler", line 336, in <module>
    args.func(args)
  File "/opt/conda/miniconda3/envs/ptr/bin/tb-profiler", line 83, in main_profile
    results = pp.profiler(conf_file=conf_file,prefix=args.dir+"/"+args.prefix,r1=args.read1,r2=args.read2,bam_file=args.bam,call_method=args.call_method,min_depth=args.min_depth,threads=args.threads,platform=args.platform,mapper=args.mapper,run_delly=True,af=args.af,caller=args.caller)
TypeError: profiler() got an unexpected keyword argument 'caller'
```
I then upgraded pathogen-profiler from 1.3 to 1.5 via
```
conda install pathogen-profiler=1.5
``` 
and now it works. I suggest to upgrade the bioconda recipe and update the dependency to
```
pathogen-profiler>=1.3
```
in [meta.yaml](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/tb-profiler/meta.yaml).

Thanks for the cool software!

**Comment by jodyphelan** [comment]
Hi Peter,

Thanks for the issue report, it should be fixed with the latest commit to bioconda.
Let me know if you find anything else!

Jody
