### ISSUE TITLE
snpEff proxy issue again with v5.0

### ISSUE THREAD

**Issue by pmenzel** [jodyphelan/TBProfiler#193]
Well, that's a bit frustrating..

The previous fix https://github.com/jodyphelan/TBProfiler/issues/188#issuecomment-972673189 does not seem to work with SnpEff 5.0e

```
>snpEff -Djava.net.useSystemProxies=true download -v Mycobacterium_tuberculosis_h37rv
00:00:00        SnpEff version SnpEff 5.0e (build 2021-03-09 06:01), by Pablo Cingolani
00:00:00        Command: 'download'
00:00:00        Reading configuration file 'snpEff.config'. Genome: 'Mycobacterium_tuberculosis_h37rv'
00:00:00        Reading config file: /home/ptr/temp/3/snpEff.config
00:00:00        Reading config file: /opt/conda/miniconda3/envs/tb403/share/snpeff-5.0-1/snpEff.config
00:00:00        done
00:00:00        Downloading database for 'Mycobacterium_tuberculosis_h37rv'
00:00:00        Connecting to https://snpeff.blob.core.windows.net/databases/v5_0/snpEff_v5_0_Mycobacterium_tuberculosis_h37rv.zip
java.lang.NoSuchMethodError: java.lang.String.isBlank()Z
        at org.snpeff.util.Download.parseProxyEnv(Download.java:231)
        at org.snpeff.util.Download.proxy(Download.java:290)
        at org.snpeff.util.Download.openConnection(Download.java:200)
        at org.snpeff.util.Download.download(Download.java:122)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.downloadAndInstall(SnpEffCmdDownload.java:32)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.runDownloadGenome(SnpEffCmdDownload.java:86)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdDownload.run(SnpEffCmdDownload.java:72)
        at org.snpeff.SnpEff.run(SnpEff.java:1188)
        at org.snpeff.SnpEff.main(SnpEff.java:168)
00:00:00        Logging
00:00:01        Done.
```

Java version is:
```
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Zulu 8.56.0.21-CA-linux64) (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Zulu 8.56.0.21-CA-linux64) (build 25.302-b08, mixed mode)
```

I will try to figure it out. Do you happen to know if the source code of snpEff 5 is available somewhere? The zip file that bioconda uses only contains the bytecode.

**Comment by pmenzel** [comment]
Ah the source code seems to be the one on github: https://github.com/pcingola/SnpEff/

and the relevant file is: https://github.com/pcingola/SnpEff/blob/master/src/main/java/org/snpeff/util/Download.java

**Comment by pmenzel** [comment]
Looks like openjdk 1.8 does not implement `String.isBlank()`, [which seems to only exist since OpenJDK 11](https://cr.openjdk.java.net/~iris/se/12/latestSpec/api/java.base/java/lang/String.html#isBlank()).

So, I tried to install openjdk 11 into the conda environment, but that in turn downgraded delly and tb-profiler:
```
Downgrade:
────────────────────────────────────────────────────────────────────────────────────

  bowtie2              2.4.4  py39hbb4e92a_0       installed                      
  bowtie2              2.4.2  py39hc9c6fcd_2       bioconda/linux-64        Cached
  delly                0.8.7  hf3ca161_0           installed                      
  delly                0.7.6  0                    bioconda/linux-64          2 MB
  tb-profiler          4.0.3  pypyh5e36f6f_0       installed                      
  tb-profiler         2.8.14  pypyh3252c3a_0       bioconda/noarch            9 MB

```

**Comment by pmenzel** [comment]
At least the download of the genome with snpEff works with openjdk11, even without the `-Djava.net.useSystemProxies=true` argument, as it looks for the `http_proxy` system variable.

**Comment by pmenzel** [comment]
Did another `mamba install tb-profiler=4.0.3` and it decided to keep openjdk 11 in the environment and it works now!

**Comment by pmenzel** [comment]
The workaround is to specify the openjdk version upon creating the conda environment:  
`mamba create -n tbprofiler403 openjdk=11.0.8 tb-profiler=4.0.3`

Maybe the openjdk version could be specified in https://github.com/bioconda/bioconda-recipes/blob/master/recipes/tb-profiler/meta.yaml

**Comment by jodyphelan** [comment]
Hi @pmenzel ,

Thanks for looking into this! So the solution would be to drop `-Djava.net.useSystemProxies=true` from the snpEff call?

**Comment by pmenzel** [comment]
The argument `-Djava.net.useSystemProxies=true` can be omitted, as snpEff 5 checks the environment variables by itself.
Important is to use openjdk 11. I used `openjdk=11.0.8` in conda, which worked.

**Comment by jodyphelan** [comment]
Ok I'll make sure to put openjdk in the recipe
